[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "atspm"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "pytz",
    "plotly"
]

[project.scripts]
atspm = "atspm.cli:main"